apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander-deployment
  labels:
    app: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        env:
        - name: REDIS_HOSTS
          value: "local:redis-service:6379"
        ports:
        - containerPort: 8081
      nodeSelector:
        kubernetes.io/arch: arm64
